services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./init-multiple-dbs:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.3.2
    command: start-dev --http-port=8080
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak?currentSchema=keycloak
      KC_DB_USERNAME: keycloak_user
      KC_DB_PASSWORD: ${KEYCLOAK_DB_PASSWORD}
      KC_HOSTNAME: ${KEYCLOAK_HOSTNAME}
    ports:
      - "8080:8080"
    depends_on:
      - postgres

  user-service:
    image: user-service:latest
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - WAITQUE_DB_PASSWORD=${WAITQUE_DB_PASSWORD}
      - AWS_REGION=us-east-1
      - KEYCLOAK_URL=http://waitque-alb-1208411922.us-east-1.elb.amazonaws.com
    depends_on:
      - postgres
      - keycloak

  company-service:
    image: company-service:latest
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - WAITQUE_DB_PASSWORD=${WAITQUE_DB_PASSWORD}
      - COMPANY_SERVICE_CLIENT_SECRET=${COMPANY_SERVICE_CLIENT_SECRET}
      - CDN_BASE_URL=http://dgzyzoic2eg8w.cloudfront.net
      - AWS_REGION=us-east-1
      - KEYCLOAK_URL=http://waitque-alb-1208411922.us-east-1.elb.amazonaws.com
    depends_on:
      - postgres
      - keycloak

  customer-service:
    image: customer-service:latest
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - WAITQUE_DB_PASSWORD=${WAITQUE_DB_PASSWORD}
      - CUSTOMER_SERVICE_CLIENT_SECRET=${CUSTOMER_SERVICE_CLIENT_SECRET}
      - CDN_BASE_URL=http://dgzyzoic2eg8w.cloudfront.net
      - AWS_REGION=us-east-1
      - KEYCLOAK_URL=http://waitque-alb-1208411922.us-east-1.elb.amazonaws.com
    depends_on:
      - postgres
      - keycloak

volumes:
  postgres_data:
